---
- name: restart loki
  become: true
  systemd:
    daemon_reload: true
    name: loki
    state: restarted

- name: reload loki
  become: true
  systemd:
    name: loki
    state: reloaded

- name: restart promtail
  become: true
  systemd:
    daemon_reload: true
    name: promtail
    state: restarted

- name: reload promtail
  become: true
  systemd:
    name: promtail
    state: reloaded
